<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textProducts</name>
   <tag></tag>
   <elementGuidId>4c04e8a3-a366-497d-a3f2-d6c19482b0ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(text(),'Products')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(text(),'Products')]</value>
      <webElementGuid>50d5ff91-2007-4c43-9080-dbded750caa0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
