<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textYourCart</name>
   <tag></tag>
   <elementGuidId>f8f0b446-b417-4ae2-9e16-340d95fb87ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@class='title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@class='title']</value>
      <webElementGuid>1e8538b6-8088-4e8a-b26c-b1e5d508542b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
